### ISSUE TITLE
При обновлении Наборов по кнопке Обновить временная таблица попадает в Наборы

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#10]
При обновлении Наборов по кнопке Обновить временная таблица попадает в Наборы (Даже если нажать Нет на контрольном вопросе)
![image](https://user-images.githubusercontent.com/123389136/214594263-bf4d8e59-4fe2-49e1-8bdf-6dfa2cee8085.png)
![image](https://user-images.githubusercontent.com/123389136/214594311-66679103-23d3-4bf6-b928-2d80396a986d.png)

**Comment by vandalsvq** [comment]
В ошибке #4 я решал данный вопрос. Какая версия в момент проверки стояла?

**Comment by vandalsvq** [comment]
Решено в 1.0.7.2
