### ISSUE TITLE
При обновлении списка областей (в случае если способ вывода области указан "Перенос строки") обновляются значения параметров входящих в эту область.

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#102]
![image](https://github.com/vandalsvq/printwizard/assets/123389136/690f509f-5692-4f66-be62-62cd2406e833)

**Comment by VarvaraKlinskaya** [comment]
Дополнение: Меняется Имя параметра, Исчезает "1" из наименования.
![image](https://github.com/vandalsvq/printwizard/assets/123389136/dae84670-187d-4685-9dbe-d0f608ab688f)

**Comment by vandalsvq** [comment]
Исчезновение 1 нормально. для переноса строки имена параметров очищаются от индексов в окончании.
В релизе 2023.3.1 изменено поведение заполнения при изменении способа вывода области.
