### ISSUE TITLE
Ошибка при оформлении поля с помощью Редактора

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#11]
Ошибка при оформлении поля с помощью Редактора если Пол=авто
![image](https://user-images.githubusercontent.com/123389136/214595893-e1693239-2edd-4e4f-80d0-d5b048be050e.png)
![image](https://user-images.githubusercontent.com/123389136/214596230-3f14f654-9e97-4250-bca9-a71cacaaf30f.png)

**Comment by vandalsvq** [comment]
Прошу проверить на тестовом релизе 1.0.7.2 (который с описание о программе).

**Comment by VarvaraKlinskaya** [comment]
Исправлено. Закрываю.
