### ISSUE TITLE
Через веб клиента не могу загрузить макет с диска

### ISSUE THREAD

**Issue by AniskovaIrina** [vandalsvq/printwizard#12]
Ошибка при вызове метода контекста (ВыбратьАсинх)
{КонструкторПечатныхФорм ОбщийМодуль.pw_СлужебныйКлиент.Модуль(790)}:	РезультатВыбора = Ждать Диалог.ВыбратьАсинх();
по причине:
{КонструкторПечатныхФорм ОбщийМодуль.pw_СлужебныйКлиент.Модуль(790)}: Расширение для работы с файлами не подключено.
	РезультатВыбора = Ждать Диалог.ВыбратьАсинх();

**Comment by vandalsvq** [comment]
Проверена работа экспорта и импорта макета. Обратите внимание, необходимо установить расширение работы с файлами для корректной работы.
