### ISSUE TITLE
Ошибка при попытке выгрузить расширение

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#123]
Настройки экспорта:
![image](https://github.com/vandalsvq/printwizard/assets/123389136/d51159c4-de80-4c94-ad9f-da9dcfe562b4)
![image](https://github.com/vandalsvq/printwizard/assets/123389136/83fb645e-cc09-47f9-9f9d-0323f2224aed)
Поле объекта не обнаружено (КонструкторПечатныхФорм)
{InfostartPrintWizard ОбщийМодуль.pw_Экспорт.Модуль(0)}:
{InfostartPrintWizard ОбщийМодуль.pw_Экспорт.Модуль(0)}:
{InfostartPrintWizard ОбщийМодуль.pw_ЭкспортВызовСервера.Модуль(51)}:Возврат pw_Экспорт.НастройкиРасширения(Параметры);
{InfostartPrintWizard ОбщийМодуль.pw_ЭкспортКлиентСервер.Модуль(206)}:Служебное.Расширение.Настройки = pw_ЭкспортВызовСервера.НастройкиРасширения(Параметры);
{InfostartPrintWizard Обработка.pw_Экспорт.Форма.Форма.Форма(777)}:Событие = pw_ЭкспортКлиентСервер.ПолучитьРасширение(Параметры);
{InfostartPrintWizard Обработка.pw_Экспорт.Форма.Форма.Форма(940)}:Возврат ВыполнитьЭкспортРасширения(ЭтотОбъект);
{InfostartPrintWizard

**Comment by vandalsvq** [comment]
Закрыта в 2024.1.8
