### ISSUE TITLE
Исправить подсказку в настройках переноса строки

### ISSUE THREAD

**Issue by NastyaMoldanova** [vandalsvq/printwizard#23]
изменить название подсказки в настройках переноса с ЗначениеЯчейки на ЗначениеСтроки
![image](https://user-images.githubusercontent.com/122966680/215681976-a4287d1d-cb66-4c10-9198-89c54c2a1bc1.png)

**Comment by vandalsvq** [comment]
Исправлено. В подсказке указано имя параметра "ЗначениеСтроки"
