### ISSUE TITLE
ЗУП внешняя печатная форма из PW - при печати ошибка в некоторых документах, в копии по этим же документам ошибки нет

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#26]
![image](https://user-images.githubusercontent.com/123389136/217510165-a20f3be5-f7b4-48b6-8070-375c249ec878.png)

**Comment by vandalsvq** [comment]
@VarvaraKlinskaya версия используемые расширений какая? Необходимо проверить на 1.0.7.3

**Comment by vandalsvq** [comment]
Повтор проблемы #11. Решено в 1.0.7.2+
