### ISSUE TITLE
Ошибка при выгрузке расширения во внешний файл Версия 1.0.7.3

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#27]
![image](https://user-images.githubusercontent.com/123389136/217510995-9cd39a2b-7882-4c4d-8dbf-ed41fd20ce61.png)

**Comment by vandalsvq** [comment]
Изменено в версии 1.0.7.4
Временное решение для 1.0.7.3. В ИБ (с помощью которой программа создает расширение) необходимо добавить любое расширение. Чтобы программе было что удалить ))))
