### ISSUE TITLE
Ошибка. Версия PrintWizard: Мастер печатных форм (1.0.7.4). Печатную форму не могу выгрузить в файл

### ISSUE THREAD

**Issue by AniskovaIrina** [vandalsvq/printwizard#38]
<img width="382" alt="image" src="https://user-images.githubusercontent.com/72007731/220310908-b19f24de-52fe-4f83-9159-97050fc01e05.png">

**Comment by vandalsvq** [comment]
Исправлено в версии 1.0.7.5
