### ISSUE TITLE
Ошибка при обновлении наборов

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#4]
При обновлении наборов добавляется временная таблица (не должна).
![image](https://user-images.githubusercontent.com/123389136/214071660-41cf6622-2395-4ec4-86e7-458aeb36d8d7.png)

**Comment by vandalsvq** [comment]
Исправлено в релизе 1.0.7.2. Временные таблицы не выводятся в наборы по умолчанию
