### ISSUE TITLE
При попытке добавить кнопку печати в журнал документов

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#46]
![image](https://user-images.githubusercontent.com/123389136/221567742-e44b9396-a833-4f48-9e9d-a95c5771c451.png)

**Comment by vandalsvq** [comment]
Возможность подключения журнала в списке объектов отключена в релизе 1.0.8.6
Необходимо проверить появление команды печати в журналах

**Comment by vandalsvq** [comment]
Решено в 1.1.1.1

**Comment by vandalsvq** [comment]
Выполнено в 1.1.1.3
Команда печати добавляется к конкретному документу, программа автоматически добавляет команды в журнал
