### ISSUE TITLE
(Веб-клиент) При выборе Заполнения значения ячейки через панель свойств (см. фото) полностью исчезает текст в ячейке

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#47]
![image](https://user-images.githubusercontent.com/123389136/221870740-79795816-3a5e-4e69-8f1a-1eadbee463a8.png)

**Comment by vandalsvq** [comment]
Особенность поведения платформы в веб-клиенте таково, что при изменении с Текста на Параметр, текст как бы очищается, но значение Параметр не заполняется. При этом если вернуть назад Текст значение в свойствах становится как надо. 

Выполнена небольшая доработка, чтобы свойства отображались корректно в дополнительной панели, однако изменение данного поведения не планируется
