### ISSUE TITLE
(Веб-клиент) ошибка при снятии флага (см. картинку)

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#48]
![image](https://user-images.githubusercontent.com/123389136/222420796-35aeaa94-264a-4e41-abf4-b06fa3c94c30.png)

**Comment by vandalsvq** [comment]
Закрыто в релизе 1.0.8.6+
Если установлен признак "Это произвольный алгоритм" изменение признака "Это список" недоступно.
