### ISSUE TITLE
(Веб-клиент) При установлении галочки в параметрах (см. фото)

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#50]
![image](https://user-images.githubusercontent.com/123389136/223114383-f98dfaa1-f193-4028-8adf-9eb476737330.png)

**Comment by vandalsvq** [comment]
Исправлено в версии 1.0.8.6+
При установленном признаке "Произвольный алгоритм" колонка "ЭтоСписок" переходит в только просмотр
