### ISSUE TITLE
Копировать значения у параметров

### ISSUE THREAD

**Issue by NastyaMoldanova** [vandalsvq/printwizard#52]
при экспорте и загрузке макета ПФ данные из параметров данных слетают, нужно заново создавать и выбирать

**Comment by NastyaMoldanova** [comment]
![проблема](https://user-images.githubusercontent.com/122966680/223365192-8bda417d-e391-4b0e-a5af-976cfacbd32f.png)

**Comment by vandalsvq** [comment]
Исправлена в тестовой версии 1.0.8.1
