### ISSUE TITLE
Некорректно работает перенос строки в макете

### ISSUE THREAD

**Issue by NastyaMoldanova** [vandalsvq/printwizard#53]
![image](https://user-images.githubusercontent.com/122966680/224027693-32c96ada-be44-4672-b90b-5dd44e4f7cfb.png)
![image](https://user-images.githubusercontent.com/122966680/224027734-5ea56ce1-67cc-4048-9473-7f239ec9ca13.png)

При выводе на печать обрезает строку, хотя перенос строки настроен

**Comment by NastyaMoldanova** [comment]
файл скинула  с макетом печати 
где косячно переносит строку
нужно заполнить общие сведения об объекте:
"Комплекс Теаларк по производству, хранению и отгрузке сжиженного природного газа в районе реки Бирь" РФ, РБ, Бирский район, в районе поселка Бурново

**Comment by vandalsvq** [comment]
@NastyaMoldanova в шаблоне контрольной строки уменьши число символов "А" до того, чтобы на новой строке было 5-7 символов, не более. Проверь шрифт (Times New Roman, 11)

На контрольном примере смог добиться подобного поведения только если количество символов "А" на переносе большое, в остальных случаях отрабатывало корректно.

**Comment by NastyaMoldanova** [comment]
![image](https://user-images.githubusercontent.com/122966680/224950472-dcc3afe6-4f51-4b16-b093-0a6942df2b9a.png)
я не понимаю что значит на новой строке? может быть есть какое-то общее количество симвлово "А", которое даст корректный перенос?

**Comment by vandalsvq** [comment]
@NastyaMoldanova по моему мы с тобой этот вопрос разобрали и его можно снимать?
