### ISSUE TITLE
1.0.8.1: Ошибка при попытке экспорта во внешнюю обработку

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#55]
![image](https://user-images.githubusercontent.com/123389136/224712961-a6018061-9f7b-446e-bb04-d7cbfe3ed2cc.png)

**Comment by vandalsvq** [comment]
Исправлено в релизе 1.0.8.1 после 14.03.23

**Comment by vandalsvq** [comment]
повтор #54
