### ISSUE TITLE
1.0.8.1: При блокировке Макета всплывающая информационная панель остается пустой, при повторном открытии формы появляется текст

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#56]
![image](https://user-images.githubusercontent.com/123389136/224714103-26a306fa-3feb-4df6-9870-3a824b468eb8.png)

**Comment by VarvaraKlinskaya** [comment]
Еще когда открыто свернутое окно, то информационная панель не появляется при блокировке, а если развернуть на весь экран, то появляется и больше не исчезает.
![image](https://user-images.githubusercontent.com/123389136/224724884-4fcb4873-7879-4a52-a20e-14754c84ee6b.png)

**Comment by vandalsvq** [comment]
@VarvaraKlinskaya 

> Еще когда открыто свернутое окно, то информационная панель не появляется при блокировке, а если развернуть на весь экран, то появляется и больше не исчезает.

обрати внимание, у тебя форма по высоте не вся отображена
и в целом, регулирование высоты отображения формы при изменении - это стандартное поведение платформы

**Comment by vandalsvq** [comment]
Исправлено в релизе 1.0.8.5
