### ISSUE TITLE
1.0.8.1: Флаг "Это реестр"

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#57]
Устанавливаю галочку Это реестр:
![image](https://user-images.githubusercontent.com/123389136/224717461-2cd09446-55cd-49d0-bbfd-aee19599fef4.png)

При печати по нескольким объектам в печатную форму попадает только первый:
![image](https://user-images.githubusercontent.com/123389136/224717340-b1d3bf28-a4ce-42c6-af0f-0c4f02f377dd.png)

**Comment by vandalsvq** [comment]
Отклонено. В макете должны быть области с повторением печати, тогда для списка данных будет выведена одна ПФ со списком (таблицей). Иначе формируется 1 ПФ на одну ссылку.
