### ISSUE TITLE
Ошибка при добавлении в наборы поле доп. реквизита

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#58]
![image](https://user-images.githubusercontent.com/123389136/226841423-08d73fdf-7810-4e64-b1ca-258dda3bf509.png)

![image](https://user-images.githubusercontent.com/123389136/226841363-1a24a6ad-5173-4e07-89e8-fe5c18be3933.png)

**Comment by vandalsvq** [comment]
@VarvaraKlinskaya прошу проверить на 1.0.8.5

**Comment by VarvaraKlinskaya** [comment]
Ошибка не исправлена 
![image](https://github.com/vandalsvq/printwizard/assets/123389136/2af3661c-1af6-4b7d-8de6-4a6a5c3056b2)

**Comment by vandalsvq** [comment]
Исправлено в 1.0.8.6
