### ISSUE TITLE
При добавлении поля доп. реквизита в наборы не определяются метаданные?

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#60]
Список доп. реквизитов документа, указанного  на вкл. Метаданные ![image](https://user-images.githubusercontent.com/123389136/226875102-e0b7d5f8-dfea-4d9c-a088-bde40f4c97f5.png)

При добавлении набора доп. реквизита не подтягиваются доп. реквизиты выбранных метаданных ![image](https://user-images.githubusercontent.com/123389136/226875220-5ed0952d-baab-4324-b103-58583b50e425.png)

При создании из формы выбора не привязываются ни к какому объекту, добавляется как неиспользуемый 
![image](https://user-images.githubusercontent.com/123389136/226876395-a2db9ee9-5f2e-4c24-9905-14e4a5df798c.png)

**Comment by vandalsvq** [comment]
Если доп. реквизитов и свойств для текущего поля не обнаружено добавлено предупреждение
Релиз 1.0.8.5
