### ISSUE TITLE
Сделать меню слева при выводе на печать нескольких разделов

### ISSUE THREAD

**Issue by NastyaMoldanova** [vandalsvq/printwizard#61]
Сделать возможность выводить на печать сразу все листы АВК
(как в АОСР - меню слева, переключение между листами)

и возможность печатать каждый лист отдельно или все вместе

![image](https://user-images.githubusercontent.com/122966680/228788196-eb8d4a0f-05d9-4b30-bb6c-b29052129fc3.png)

**Comment by vandalsvq** [comment]
Реализовано в 1.0.8.2
