### ISSUE TITLE
1.0.8.1 Ошибка при открытии печатной формы установленной как внешняя обработка

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#63]
![image](https://user-images.githubusercontent.com/123389136/231456853-fa879f5a-de88-488c-a0ff-2ee48f8615c7.png)

**Comment by NastyaMoldanova** [comment]
Подтверждаю ошибку, у меня возникла в Петоне 25.05.23

**Comment by vandalsvq** [comment]
Прошу проверить на 1.0.8.2

**Comment by vandalsvq** [comment]
@NastyaMoldanova @VarvaraKlinskaya я просил проверить на версии 1.0.8.2 и старше
