### ISSUE TITLE
Ошибка при редактировании области (объединить/разбить строки)

### ISSUE THREAD

**Issue by NastyaMoldanova** [vandalsvq/printwizard#64]
![image](https://github.com/vandalsvq/printwizard/assets/122966680/fc905bb2-95c9-4af4-9ca3-0185812b1b57)
![image](https://github.com/vandalsvq/printwizard/assets/122966680/85c64a9a-3412-40c6-accf-df941ad60d0c)

**Comment by NastyaMoldanova** [comment]
релиз 1.0.8.2

**Comment by vandalsvq** [comment]
Исправлено в 1.0.8.5
@NastyaMoldanova прошу подтвердить
