### ISSUE TITLE
События - добавление/удаление комментария

### ISSUE THREAD

**Issue by NastyaMoldanova** [vandalsvq/printwizard#69]
Если в событии был указан код, то при изменении этого кода в комментарий - выходит ошибка:
![image](https://github.com/vandalsvq/printwizard/assets/122966680/04eafb8b-a3b6-47bc-a4a9-f89a5c7a0230)

Значение не является значением объектного типа (Объект)
{КонструкторПечатныхФорм Справочник.pw_Макеты.Форма.ФормаЭлементаКОРП.Форма(4032)}:МассивСтрок = pw_ОбщегоНазначенияКлиентСервер.СтрокиТаблицыПоИдентификатору(Форма.Объект.АлгоритмыОбработки, Идентификаторы);
{КонструкторПечатныхФорм Справочник.pw_Макеты.Форма.ФормаЭлементаКОРП.Форма(3194)}:ОбновитьРеквизитыТабЧастиАлгоритмыОбработки(ДопПараметры.Идентификатор);
{КонструкторПечатныхФорм Обработка.pw_КонсольКода.Форма.Форма.Форма(314)}:ЭтотОбъект.Закрыть(Результат);
{КонструкторПечатныхФорм Обработка.pw_КонсольКода.Форма.Форма.Форма(227)}:ЗаписатьИЗакрытьНаКлиенте();

**Comment by vandalsvq** [comment]
Исправлено в 1.0.8.6
