### ISSUE TITLE
Вкладка Наборы. Пожелание по удобству использования

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#7]
Необходимо чтобы при первичном заполнении Наборов не было необходимости нажимать на кнопку Обновить повторно, чтобы заполнились Поля набора.
![image](https://user-images.githubusercontent.com/123389136/214529686-232343c7-39ff-49c4-9dd6-432a67d3630d.png)

**Comment by vandalsvq** [comment]
Реализовано в 1.1.0.10
