### ISSUE TITLE
При загрузке внешней обработки - расположение слетает и заново задать нельзя

### ISSUE THREAD

**Issue by NastyaMoldanova** [vandalsvq/printwizard#70]
Когда в базу гружу ПФ как внешнюю обработку - то расположение печатки (объект метаданных) слетает
![image](https://github.com/vandalsvq/printwizard/assets/122966680/f4c25c64-58a8-420d-936e-a022f0cf327c)

а если самим выбрать из списка его и записать
выходит ошибка и не дает записать эту печатную форму

Метод объекта не обнаружен (ДобавитьКомандыПечати)
{ОбщийМодуль.УправлениеПечатью.Модуль(2440)}:Источник.Менеджер.ДобавитьКомандыПечати(ДобавляемыеКомандыПечати);
{ОбщийМодуль.УправлениеПечатью.Модуль(1560)}:ОбщегоНазначения.ОбъектМетаданныхПоИдентификатору(Объект, Ложь));
{Справочник.ДополнительныеОтчетыИОбработки.Форма.ФормаЭлемента.Форма(1375)}:КомандыПечатиОбъекта = МодульУправлениеПечатью.СтандартныеКомандыПечатиОбъекта(Объект.Назначение[0].ОбъектНазначения);
{Справочник.ДополнительныеОтчетыИОбработки.Форма.ФормаЭлемента.Форма(231)}:ЗаполнитьКоманды();
{Справочник.ДополнительныеОтчетыИОбработки.Форма.ФормаЭлемента.Форма(537)}:Успех = Записать(ПараметрыЗаписи);
{Справочник.ДополнительныеОтчетыИОбработки.Форма.ФормаЭлемента.Форма(526)}:ВыполнитьОбработкуОповещения(Обработчик, КодВозвратаДиалога.ОК);
{Справочник.ДополнительныеОтчетыИОбработки.Форма.ФормаЭлемента.Форма(384)}:ЗаписатьНаКлиенте(Истина);

**Comment by vandalsvq** [comment]
Для данного объекта механизм команд печати не подключен. Исправить не выйдет,поскольку это механизм бсп. Но можно поставить защиту наверное или предупреждение при выгрузке в обработку.

**Comment by vandalsvq** [comment]
Увы при выгрузке в обработку (и в другой момент) проверить использование подключаемых команд в объекте невозможно. Никаких предупреждений тоже не выйдет сделать. Задачу в текущем варианте увы никак не решить
