### ISSUE TITLE
1.8.0.4 Аварийное завершение при попытке Заблокировать форму после Записи

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#71]
![image](https://github.com/vandalsvq/printwizard/assets/123389136/80b5dc0d-f4d4-4e80-a4c1-a011855f6339)

**Comment by vandalsvq** [comment]
@VarvaraKlinskaya Нужен файл xml с ошибкой или журнал регистрации глянь, может там какие следы есть

**Comment by vandalsvq** [comment]
Повторить не удается, в логах увы ничего существенного чтобы помогло. Возможно это ошибка платформы 23. Перевел в статус "Не подтверждается". Проверим на новой платформе

**Comment by vandalsvq** [comment]
Данная ошибка возникает в платформе 8.3.23, поскольку изменение свойства ИзменятьСоставСтрок на клиенте вызывает аварийное завершение.

**Comment by vandalsvq** [comment]
Решено в 1.1.1.1
