### ISSUE TITLE
Ошибка при удалении значения набора в параметрах области

### ISSUE THREAD

**Issue by NastyaMoldanova** [vandalsvq/printwizard#76]
Когда в параметре у значения нажимаешь на крестик, выходит ошибка

Поле объекта не обнаружено (КлючСтрокиНабора)
{InfostartPrintWizard Справочник.pw_Макеты.Форма.ФормаЭлементаКОРП.Форма(2374)}:ТекущиеДанные.КлючСтрокиНабора	= "";
![image](https://github.com/vandalsvq/printwizard/assets/122966680/f757b99e-47c2-429d-b432-0d31e00c581b)

нажимаешь ок - пропадает

**Comment by vandalsvq** [comment]
Исправлено в 1.1.0.3
