### ISSUE TITLE
Удаление областей в макете

### ISSUE THREAD

**Issue by NastyaMoldanova** [vandalsvq/printwizard#77]
Когда создан макет, области заданы
нажимаешь на область - удалить
выходит ошибка

**Comment by NastyaMoldanova** [comment]
Ошибка при вызове метода контекста (ПолучитьОбласть)
{InfostartPrintWizard ОбщийМодуль.pw_КонструкторКОРП.Модуль(1280)}:Область = ТабличныйДокумент.ПолучитьОбласть(СтрокаОбласти.ИмяОбласти);
{InfostartPrintWizard ОбщийМодуль.pw_КонструкторКОРП.Модуль(665)}:ОбновитьОбластиМакетаПараметрыИзТабличногоДокумента(Форма.Объект, Форма.ТабличныйДокумент, СтрокаОбласти);
{InfostartPrintWizard Справочник.pw_Макеты.Форма.ФормаЭлементаКОРП.Форма(4987)}:pw_КонструкторКОРП.ЗаполнитьОбластиМакетаПараметрыИзДокумента(ЭтотОбъект, СтрокаОбласти);
{InfostartPrintWizard Справочник.pw_Макеты.Форма.ФормаЭлементаКОРП.Форма(1001)}:ОбновитьОбластиМакетаПараметрыИзОбластиНаСервере(ТекущиеДанные.ПолучитьИдентификатор());

по причине:
Область не найдена: Область2

**Comment by NastyaMoldanova** [comment]
> Когда создан макет, области заданы - нажимаешь на область - удалить  - выходит ошибка

**Comment by NastyaMoldanova** [comment]
и потом нельзя отменить действие - вернуть обратно
![image](https://github.com/vandalsvq/printwizard/assets/122966680/ac1811a5-3487-4a6f-96a8-b4ed8b4da847)

**Comment by vandalsvq** [comment]
Исправлено в 1.1.0.3
