### ISSUE TITLE
Пожелание автозаполнение Параметров по названию

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#8]
Чтобы значения параметров в ТЧ Параметры области автоматически заполнялись при совпадении имени Значения с именем Параметра, без указания набора в ТЧ Области макета
![image](https://user-images.githubusercontent.com/123389136/214576688-d0aca4ef-230b-4507-8fbc-39f4c65bde2e.png)

**Comment by vandalsvq** [comment]
Реализовано в 1.1.1.3
