### ISSUE TITLE
Ошибка при печати с пустыми настройками переноса строки

### ISSUE THREAD

**Issue by NastyaMoldanova** [vandalsvq/printwizard#81]
![image](https://github.com/vandalsvq/printwizard/assets/122966680/efe1bdfd-9d73-498b-b923-f097d25238a4)

Если задаю перенос строки, но не задаю там настройки, выходит ошибка, по которой это непонятно)))
возможно ли вписать данные области, в которой не заданы настройки переноса? для быстрого нахождения этого косяка в макете

**Comment by vandalsvq** [comment]
Добавлен контроль корректности заполнения областей
