### ISSUE TITLE
Не сработало автоматическое обновление набора

### ISSUE THREAD

**Issue by NastyaMoldanova** [vandalsvq/printwizard#82]
Внесла в запросы значения из универсальных ролей
Хотела в соединения добавить, а там нет
Оказывается, набор не обновился автоматически

это связано с тем, что я Значения именно ввела?
Ведь если просто вносишь данные, они сразу обновляются в наборе
<img width="1068" alt="Screenshot_2" src="https://github.com/vandalsvq/printwizard/assets/122966680/1ad203dd-8660-4dbd-ac06-949efbfef032">
<img width="892" alt="Screenshot_3" src="https://github.com/vandalsvq/printwizard/assets/122966680/28c79476-d175-4cd0-a4bb-2e77d6c6eb9e">

**Comment by vandalsvq** [comment]
@NastyaMoldanova При автообновлении поля обычно добавляются в конце списка, и не сортируются по алфавиту. По скринам я не вижу, вполне возможно поля внизу были. 
Разницы между тем, как поля добавлены (поле запроса, значение, параметр) нет, с точки зрения набора

**Comment by vandalsvq** [comment]
@NastyaMoldanova а еще, кнопка обновить есть, находится в Еще. Ну если реально все таки поля не появились.
Хотя я все еще сомневаюсь, что дело в ЗНАЧЕНИЕ

**Comment by NastyaMoldanova** [comment]
скрин приложила не весь, я весь набор пересмотрела с начала до конца)

набор я обновила руками через кнопку, и данные значения подтянулись из запроса

**Comment by vandalsvq** [comment]
@NastyaMoldanova попробуй в других макетах аналогичные изменения в запросах. Возможно есть другая закономерность .

**Comment by NastyaMoldanova** [comment]
ошибку повторить не смогла в других макетах
как только не крутила
видимо полтергейст завелся вчера ночью)))
наверно, можно закрывать задачу)

**Comment by vandalsvq** [comment]
Замечено, если текст запроса отредактирован в поле текстового документа на форме (без спец. редактора, конструктора или консоли), обновление может быть не выполнено.
