### ISSUE TITLE
В Конструкторе запроса переименовала таблицу и перешла на вкладку Связи

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#83]
![image](https://github.com/vandalsvq/printwizard/assets/123389136/341fa0d0-f113-4f8d-8273-b89d42396e99)

**Comment by VarvaraKlinskaya** [comment]
Я не щелкнула на пустое место и перешла на другую вкладку, переименование не сохранилось, так работает конструктор и с этим ничего не сделать? Замечала такое и ранее.

**Comment by vandalsvq** [comment]
Ошибка происходит в типовом конструкторе запросов. Решение - использовать конструктор из Toolkit. 
Или смириться
