### ISSUE TITLE
Ошибка если не обновлен список параметров, можно ли сделать более понятно?

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#84]
![image](https://github.com/vandalsvq/printwizard/assets/123389136/f6f0e0d6-c734-4b07-bd67-33e4ebc4ea51)

**Comment by vandalsvq** [comment]
- Добавлена проверка параметров перед записью
- Изменен текст сообщений при ошибках формирования печатных форм для более понятного представления ошибки
