### ISSUE TITLE
Пожелание сделать выпадающий список доступных Параметров из наборов

### ISSUE THREAD

**Issue by VarvaraKlinskaya** [vandalsvq/printwizard#9]
Сделать выпадающий список доступных Параметров из наборов
![image](https://user-images.githubusercontent.com/123389136/214579306-f046c85d-1d2a-47a5-b628-b3e314b7e85b.png)

**Comment by vandalsvq** [comment]
Отклонено

Данное поле предполагает заполнение вручную. Данных для выпадающего списка нет, программа сама не может определить планируемое имя параметра.
